### ISSUE TITLE
[BUG] COM Radios do not update display

### ISSUE THREAD

**Issue by ElSrJuez** [flybywiresim/a32nx#1079]
**Mod Version** 3.1

**Describe the bug**

The A320 doesn't update the COM radio frequencies on the Virtual Cockpit display when using SimConnect Events to change the frequency value or when switching from Active/Standby

**To Reproduce**

1. Launch a flight
2. Update the radio frequencies using SimConnect events (i.e., Axis and Ohs)

**Expected behavior**

The A320 VC Radio display should maintain display of current frequencies (active and standby) on all updates.

**Actual behavior**

3.The Neo Radio display doesnt show the change
4. By using other apps to read radio variables (i.e., vPilot) the updated frequencies show
5. Other default Asobo aircraft update display just fine

**References**

https://forums.flightsimulator.com/t/logitech-switch-panel/173895/12

**Additional context**

This is important for interacting with the cockpit via SimConnect

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub):
ElSrJuez

**Comment by Watsi01** [comment]
Can confirm that. It's an Asobo bug.

**Comment by ElSrJuez** [comment]
Small bit of info: When switching from VHF2 to VHF1 using VC buttons, the current COM1 display will update to the tuned frequency (but not the standby).

**Comment by ElSrJuez** [comment]
I still think that there is no fundamental reason why this should not work, so did a little extra digging.

Most SimConnect avionic controllers use the COM_RADIO_WHOLE_INC and COM_RADIO_WHOLE_DEC (as well as COM_RADIO_FRAC_INC/_DEC) events. The issue as described is that those events are not triggering updates on the Neo Virtual Cockpit Radios.

I just discovered (via another tool that captures this) that the COM rotary buttons on the Neo VC actually trigger the **COM_STBY_RADIO_SET_HZ** event instead.

Also, that the **COM_STBY_RADIO_SWAP** event may not have a handler on the VC HTML Gauge, because again instead it uses **COM_RADIO_SET_HZ** and **COM_SBY_RADIO_SET_HZ** events in sequence.

https://github.com/flybywiresim/a32nx/blob/487e3741ef1e5ad7f47a81a9fd91c4379784c102/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.js

So, two possible workarounds/solutions would be:
1. Add code to monitor the events for the WHOLE/FRAC INC/DEC Events plus the COM_STBY_RADIO_SWAP and update the Gauge displays or
2. Rewrite the logic to use the increment/decrement/swap Simconnect events instead?

Both potentially could make the Neo compatible with a whole array of COM RADIO controllers that use SimConnect.

**Comment by lukecologne** [comment]
These events are handled by the sim itself, not the gauges. The gauges should only display Simvars that are changed by logic triggered by the events elsewhere, either in the base sim, or in other SimConnect applications such as WASM, or external ones.

**Comment by Cronch** [comment]
Hi guys,
I just wanted to say that **it is correctly working on the vanilla version** of the plane (unmodded game) but it is NOT working on this mod. (just wanted to clarify this because the original report says it is also a problem on vanilla)
Just tested it on the latest MSFS version 1.12.13.0

**Comment by rzimin** [comment]
I would second this request.
Right now Logitech radio panel, even coupled with SPAD cannot work with COM_STBY_RADIO_SET_HZ which makes it useless for such a great product.

I fully support ideas by https://github.com/flybywiresim/a32nx/issues/1079#issuecomment-729278305

**Comment by gleclere** [comment]
I would second this request too.

I'm using a Behringer X-Touch Mini usb midi device with X-Touch-Mini-FS2020 to bind encoders and buttons to MSFS actions. COM_RADIO_WHOLE/FRAC_INC/DEC events aren't working to set the standby frequency to the A32NX, while they work for the vanilla a320neo.

**Comment by ElSrJuez** [comment]
This has apparently been fixed in Vanilla but from the feedback in the past two weeks it now doesnt work in A32NX, maybe because the relevant code in A32nx points to an older Asobo codebase... or maybe because there is a new code intoduced on the FBW code.
My question is, since this has essentially been fixed... should this bug be closed now?

**Comment by Cronch** [comment]
Hi @ElSrJuez, I just tested it one more time on the A32nx mod and it is still NOT working. I think the issue should stay open because the problem is still there

**Comment by FoxtrotSierra6829** [comment]
Will probably be fixed by #3157
