### ISSUE TITLE
[BUG] Flight Deck Flickering

### ISSUE THREAD

**Issue by AeJae** [flybywiresim/a32nx#1336]
**Mod Version**
Release V0.3.1

**Describe the bug**
Everything flickers massively, caused by the displays - it all flickers in the colour of light that they give out, I've attached a clip of it happening.

**To Reproduce**
1. Load into the A32NX V0.3.1 on current sim release as of 14th Nov 2020
2. Turn on displays.

**Expected behavior**
Flight deck will either be illuminated solidly or not at all, no flickering.

**Actual behavior**
Flight deck flickers between being illuminated and not illuminated.

**References**
https://drive.google.com/file/d/1CZddLnh2iXv1ClndFHXpplkHUVFuqgYr/view?usp=sharing

**Additional context**
----

Was this working before/when did the issue start occurring?
Only ran into this since using V0.3.1

Is this a problem in the vanilla unmodded game?
I couldn't replicate without A32NX, but I couldn't definitively say no.

Discord username (if different from GitHub): Arun Geeza#8080

**Comment by Benjozork** [comment]
Fixed in latest master 😄 stable releases are not supported when MSFS updates.

**Comment by AeJae** [comment]
Ahhh I thought 0.3.1 was for that update my bad, cheers!

**Comment by DominWorks** [comment]
Hello, 

I've downloaded the latest 0.4.0 version (uploaded 6 hours ago) and I still have the same problem. The one under release page is not the latest master release? maybe i'm looking the wrong version.

**Comment by Benjozork** [comment]
Hello,

You should be looking at this:

![image](https://user-images.githubusercontent.com/4503241/96147099-fb7c1200-0ed4-11eb-8a34-46d873db4024.png)
