### ISSUE TITLE
[BUG] Deice buttons dont work

### ISSUE THREAD

**Issue by lawfulrocky** [flybywiresim/a32nx#1368]
**Mod Version**
Latest dev and release

**Describe the bug**
Deice buttons are not clickable and show fault and on at the same time

**To Reproduce**

1.spawn on the airport
2. deleted and redownload the mod
3.

**Expected behavior**
should be able to click them on and off and show correct light

**Actual behavior**
buttons not clickable and light shows fault and on

**References**
![Screenshot (22)](https://user-images.githubusercontent.com/25673245/96144947-b8b93a80-0ed2-11eb-9380-9f8fadc1b7bb.png)

**Additional context**

Was this working before/when did the issue start occurring? yes

Is this a problem in the vanilla unmodded game? no

**Comment by lawfulrocky** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/25673245/96148370-3468b680-0ed6-11eb-89d4-6f2ff3f0c5ba.png)
show the xml files not there for the deice

**Comment by Ulferno** [comment]
Have the same issue, installed version 0.4.0 and the latest MSFS.

**Comment by guifarias31** [comment]
Are you guys using [my TBM 930 mod](https://github.com/guifarias31/msfs_tbm930_project)? If so, it's conflicting with 0.4.0 and I had to remove all inertial separator changes I've made.
[Version 0.5.1](https://github.com/guifarias31/msfs_tbm930_project/releases/tag/0.5.1) is out btw.

**Comment by lawfulrocky** [comment]
Yea I have the TBM install

**Comment by Benjozork** [comment]
@guifarias31 I think we should both move to our own ModelBehavior templates 😆 thank you for your quick reaction!

Closing issue since it is caused by another addon and is resolved.

**Comment by Benjozork** [comment]
Nevermind, I am getting it without the TBM mod.

![image](https://user-images.githubusercontent.com/4503241/96215958-45084380-0f4d-11eb-87b4-447cf077be4b.png)

**Comment by Ulferno** [comment]
I have never installed the TBM mod and I have been having this issue since the japan update.

**Comment by 0nnyx** [comment]
Had the tbm mod & problem with AIce Fault ON stuck. Resolved after upgrading to latest tbm mod 0.5.1 and latest a32nx dev

**Comment by Ulferno** [comment]
Updated to a32nx dev and issue was resolved.

**Comment by lukecologne** [comment]
We recently made changes that should have fixed this issue, can anyone still report that it is still happening? If not, then we can close this.

**Comment by lukecologne** [comment]
Closing as the issue creator has not responded, and the issue is stale.
