### ISSUE TITLE
[Fehler] EFIS Control Panel without function

### ISSUE THREAD

**Issue by Onkelpuh** [flybywiresim/a32nx#2643]
**Mod Version**
Stable 0.5.1

**Describe the bug**

Switches, buttons and buttons have no function

**To Reproduce**

1. Batterie ON
2. Extern Power ON
3. boot systems

**Expected behavior**

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**Comment by Awemeter** [comment]
Follow template please

**Comment by Benjozork** [comment]
Fixed in #2659

**Comment by Onkelpuh** [comment]
Unfortunately, the problem has still not been fixed for me, the keys and buttons on the EFIS are movable with me, but nothing happens, and the buttons don't turn green after pressing, nothing happens
Furthermore, I still know the two displays of the co-pilot
current DEV loaded via downloader
