### ISSUE TITLE
[BUG] Problem with B747 FMCE

### ISSUE THREAD

**Issue by jmoureau** [flybywiresim/a32nx#2725]
**Mod Version**

Version 0.5.0 and 0.5.1

**Describe the bug**

Screens of all FMC of the B747 are off

**To Reproduce**

1. Have A32NX installed
2.Launch the game
3.Try the plane b747

**Expected behavior**

I would like to play with all aircrafts.

**Actual behavior**

I cannot use B747

Thanks for your help.

**Comment by ThatRedMelon** [comment]
This should been fixed in current master/dev by #2672

**Comment by jmoureau** [comment]
the problem is still present 
![image](https://user-images.githubusercontent.com/76614146/103150353-aa5d8980-4773-11eb-81bc-caa344f5a588.png)

**Comment by ThatRedMelon** [comment]
You've stated you are using stable version, the problem is fixed in the development version

**Comment by jmoureau** [comment]
ok .. I tested with the Dev Version, FMC are working . thanks

**Comment by jmoureau** [comment]
Thanks for your support
