### ISSUE TITLE
[BUG] Unable to get flight plan using Simbrief

### ISSUE THREAD

**Issue by joscha999** [flybywiresim/a32nx#2766]
**Mod Version**
0.5.1

**Describe the bug**
I'm unable to get all data from Simbrief, the data in the ATSU/AOC/INIT page is correctly downloaded (i.e. Flight number is correct, dep. and dest. are correct as is payload and fuel data), if I then try to do INIT/REQUEST I get the "uplink insert in prog" message but nothing further, waited for several minutes but only the TROPO was set (CO RTE, FROM/TO and FLT NBR on the INIT page are still empty) and the message still states "uplink insert in prog".
Looking at the API/txcxn/_find for my flight nbr it was created but with no departure or destination.
Any further press on REQUEST leeds to "FLT NBR IN USE".

**To Reproduce**

1. Create flight plan on Simbrief (in my case EDDH => EDDM) and generate OFP
2. Start MSFS
3. Select departure gate (in my case EDDH/Gate 13)
4. Load into sim
5. Enable batteries and ground power
6. Run ATSU/AOC/INIT/INIT DATA REQ
7. Go to INIT page and run the REQUEST

**Expected behavior**

A full flight plan is downloaded and entered in INIT as well as the F-PLN pages.

**Actual behavior**

Only TROPO is updated while the message "uplink insert in prog" is displayed until cleared or something else is done.

**References**

**Additional context**

I've seen multiple tutorials about how to use the Simbrief and as far as I can tell the steps that I posted above worked for those people, cannot tell why it does not work for me - tried several settings on Simbrief but couldn't find a difference, always leeds to the same issue.
I also took a look at the console, there is no message logged (I cleared before running the INIT/REQUEST).

Was this working before/when did the issue start occurring?
I manually installed 0.5.1 and run into this issue, trying around with different flight plans I also ran into #2746. I removed the mod from my community packages (MS Store version) and re-installed it via the downloader - after changing the ATC flight number to avoid #2746 this issue appeared.

Is this a problem in the vanilla unmodded game?
Only mods are the a32nx and the livery pack from the MSFS forums (I'm using the Lufthansa livery).

Discord username (if different from GitHub): joscha999#8860

**Comment by Richard5644** [comment]
having a similar problem.

When I hit Init request on init page I get a message "not in database", followed by "not allowed."

**Comment by wattie60** [comment]
I have exactly the same issue than Richard5644. However this feature was working well on previous versions (before 0.5.1).

**Comment by joscha999** [comment]
Some additional info: After debugging this issue some for myself (by pasting logs everywhere) I was able to narrow this issue down to the A32NX_FMCMainDisplay.js - tryUpdateFromTo(). A message before the "this.dtaManager.GetAirportByIdent(from)" is still displayed (it correctly shows "EDDH" should be searched) but that's the end of it - no further message (the next one should be either in the if (airportFrom) noting the to airport icao or in the else showing not in DB) but also no error in the console.

I've searched for the DataManager but it's not in this code-base so I assume it's an internal system from FS and I sadly have no experience with it so that's where my debugging will have to stop. I have the slight feeling that this may be something broken with my local install so I'll probably reinstall FS completely, will update this if there's any news from it.

**Comment by joscha999** [comment]
Issue solved by re-installing FS, am able to fly correctly and use all the normal Simbrief functions, not quite sure but I'd guess my navigation database broke for some reason and FS just couldn't handle it.

**Comment by 10Exahertz** [comment]
Anybody have a better solution than a complete reinstall of FS?
I am having the same issue

**Comment by Richard5644** [comment]
Interesting comments-thank you.    I did a complete clean uninstall/reinstall of FS, but still have the same problem.   I aasume the problem is still in FS somewhere, especially as I still have occasional problems with ILS approaces etc.    I guess for the moment it's something I hav e to live with

**Comment by yosefmah** [comment]
I fixed this by uninstalling and reinstalling the Navigraph database following Sim Update 3.

**Comment by christianparpart** [comment]
> 

@yosefmah can you please elaborate on "uninstalling and reinstalling the navigraph database", because I'm stuck at the same issue after GOTY update?

Thanks. :)

**Comment by Jype57** [comment]
Personally I solved my problem via Navdatacenter by deleting and reloading Airac (and charts for security) 😉
