### ISSUE TITLE
ver 0.5.1 (Horror) Turn off FMC on the 747 plane

### ISSUE THREAD

**Issue by mrctll** [flybywiresim/a32nx#2806]
The stable version turn off the FMC on the 747 plane. Fix please. Every time i want fly with 747 i must delete the A32NX mod in the community folder. Thank's

**Comment by Benjozork** [comment]
Don't ignore the provided template.

Also, there was already an issue about this and it says it's fixed in the development version. Easily found using the search function.

Closing.

**Comment by mrctll** [comment]
The developer version is not stable, it changes every day and usually does not go up or down. However it is a testing version. What does it mean it was fixed in the developer version? This is nonsense

**Comment by Benjozork** [comment]
All of our team and multiple streamers fly with the development version multiple times per day and have absolutely no problems.

It means that the issue is resolved in the development version. In addition to that, a new stable release will come with those fixes very soon.

I will advise you to remain polite in your comments.

**Comment by hotshotp** [comment]
> 
> The developer version is not stable, it changes every day and usually does not go up or down. However it is a testing version. What does it mean it was fixed in the developer version? This is nonsense

Dev version still gets tested - it's not just a testing version. Bugs in the development version are not common. Please be more respectful. Thanks.

**Comment by mrctll** [comment]
Forse voi mancate di rispetto. Ho semplicemente detto che la versione stabile non accende l'FMC del 747. Che la versione developer risolve la cosa, lascia il posto che trova perchè è una versione sviluppatore. Non capisco il vostro nervosismo. Posso benissimo metterla e toglierla a seconda dell'aereo. Gente Simpatica!.

Maybe you are disrespectful. I simply said that the stable version does not turn on the 747 FMC. That the developer version solves it, it gives up the place it finds because it is a developer version. I don't understand your nervousness. I can very well put it on and off depending on the plane. Nice People !.

**Comment by hotshotp** [comment]
> Forse voi mancate di rispetto. Ho semplicemente detto che la versione stabile non accende l'FMC del 747. Che la versione developer risolve la cosa, lascia il posto che trova perchè è una versione sviluppatore. Non capisco il vostro nervosismo. Posso benissimo metterla e toglierla a seconda dell'aereo. Gente Simpatica!.
> 
> Maybe you are disrespectful. I simply said that the stable version does not turn on the 747 FMC. That the developer version solves it, it gives up the place it finds because it is a developer version. I don't understand your nervousness. I can very well put it on and off depending on the plane. Nice People !.

I'm saying it's disrespectful because you put "horror" and "nonsense" in your post. I'm saying that the development version is called that because it has new features being developed every day. It is extensively tested and good to use normally.

**Comment by mrctll** [comment]
google translate ... sorry!
