### ISSUE TITLE
[BUG] When doing fuel calculations in MCDU, the second init page changes to "untitled"

### ISSUE THREAD

**Issue by ISibboI** [flybywiresim/a32nx#3224]
**Mod Version**

0.5.2

**Describe the bug**

I plan a flight with SIMBRIEF, then load it into the MCDU. When I go to the second INIT page and do the fuel prediction, afterwards the second INIT page empties and only shows untitled as headline. Switching to another page and back does not make it come back to normal.

**To Reproduce**

1. Perform "Preliminary cockpit preparation" checklist
2. Perform "Cockpit preparation" checklist up to "Obtain IFR clearance"
3. On the first INIT page, request the data from SIMBRIEF
4. On the second INIT page, press the ZFW/ZFWCG button such that the correct weights are entered
5. On the second INIT page, press button two below the ZFW/ZFWCG button, that calculates the block fuel. **Note** When entering block manually as given in the SIMBRIEF flightplan, the bug does not occur.
6. Shortly after confirmation of the block fuel, the second INIT page becomes empty, displaying only "untitled" at the top

**Expected behavior**

The second INIT page should show the final values of the calculations, and should in general show information instead of being empty.

**Actual behavior**

The second INIT page is competely black, except for "untitled" in the headline

**References**

**Additional context**

I first thought this might be caused by loading a flight plan that exceeds the airplanes fuel capacity, but after testing with a flight plan that surely does not exeed fuel capacity, the same issue occurred.

Was this working before/when did the issue start occurring?
I updated to 0.5.2 today using the A32NX_Downloader v0.7. I had a version from Nov/Dec 2020 before, and I believe the fuel calculations worked back then.

Is this a problem in the vanilla unmodded game?
I do not know

Discord username (if different from GitHub): ISibboI#7273

**Comment by Awemeter** [comment]
So 2 things one you are using the old installer and can find the new one here https://api.flybywiresim.com/installer secondly I have had this issue but it happened after I went direct and changed Sid and star multiple times.

**Comment by MisterChocker** [comment]
We need someone trying to replicate the issue with the console.

**Comment by tracernz** [comment]
I have seen this blank "Untitled" page before when doing DIR TO (when the flight plan manager skips to runway at IAF!). It may be unrelated to the particular issue you're seeing here, or maybe not. I'll try to capture more info next time.

**Comment by MisterChocker** [comment]
cc. @Lucky38i maybe you know something about this?

**Comment by ISibboI** [comment]
Thank you all, I have completely reinstalled the mod using the new installer, and the problem prevails.

I now found a shorter way to reproduce the bug:

 * Hop into the A320NX cold and dark, at some gate on some airport
 * Set up a flight plan starting from that airport in SimBrief

Then in the plane do the following:
 * Turn on external power
 * Go to the INIT page of the MCDU
 * Press INIT REQUEST
 * Wait until it shows AOC ACT F-PLN UPLINK
 * Press right arrow
 * Press ZFW/ZFWCG two times, waiting two seconds between presses
 * Press FUEL PLANNING two times, waiting two seconds between presses (the second time with the different prompt)
 * Wait a few seconds, and the page turns black with UNTITLED at the top and GPS PRIMARY LOST in dark orange at the bottom

**Comment by Awemeter** [comment]
Ok so I have recreated this with the stable 5.2 here is the log
I recreated it but this one is different it only breaks the int B page and the fuel pred page. The one before broke the whole mcdu. I will keep investigating and trying to break the plane.
[Untilted page.txt](https://github.com/flybywiresim/a32nx/files/5897598/Untilted.page.txt)

**Comment by tracernz** [comment]
I was unable to repro starting at NZAA with a fp of `NZAA/23L STEAL1P KARRL Y506 TPAPA TPAPA3B NZWN/16` on latest master (d7c468e1693).

**Comment by Awemeter** [comment]
> I was unable to repro starting at NZAA with a fp of `NZAA/23L STEAL1P KARRL Y506 TPAPA TPAPA3B NZWN/16` on latest master ([d7c468e](https://github.com/flybywiresim/a32nx/commit/d7c468e169338bfa8712251b5b89340a349928d7)).

This was recreated using the latest stable not the dev. I know the issue does happen on the dev but am un able to recreate on it

**Comment by MisterChocker** [comment]
Any news on this? I believe this has been fixed.

**Comment by belima** [comment]
I still get the untitled page sometimes after clicking "block confirm" but I can't figure out what triggers it. It doesn't happen every time and it sometimes comes back to normal after some time (or after some unknown things happen).

**Comment by MisterChocker** [comment]
Am I right to assume this bug no longer appeared? Since I am unable to reproduce it at all.

**Comment by ISibboI** [comment]
Did not happen to me on 0.6.x again, so might be fixed in the more recent versions.

**Comment by MisterChocker** [comment]
Alright I am going to close this, if the issue appears again one can open this issue again or open a new one.
