### ISSUE TITLE
[BUG] WorkingTitle CJ4 + specific EFIS configuration breaks ND

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/a32nx#3631]
**Mod Version**

{
  "built": "2021-02-19T13:12:57+00:00",
  "ref": "autopilot",
  "sha": "742aa91a14f231a84cab6fb7618d880d4d91820c",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**

when the efis control panel is set to CSTR, the ND does not update, it stays in the position it was in
however when pressing any other button on the panel, the ND updates as it should.

the problem ONLY happens with the working title CJ4 mod installed, and happens on EVERY branch, 

**To Reproduce**

1. Load in with WT CJ4 + A32NX Mods active
2. align ADIRS (not tested when loading in on rwy/with adirs aligned)
3. set efis control to CSTR
4. watch ND
5. set efis control to anything else
6. watch ND

**Expected behavior**

ND updates when efis control panel is set to CSTR

**Actual behavior**

 ND freezes in the posiiton it was in, and never updates. When NO efis control buttons are selected, or when ANYTHING APART FROM CSTR is selected, the ND updates as it should 

**References**

https://i.imgur.com/0l82E3S.png <- nd updating as it should - no efis modes selected
when i then press CSTR and move the aircraft to a different heading
https://i.imgur.com/o9KKPSH.png <- the heading ring at the top updates, but the ND remains in the same position as it was when i pressed the button

**Additional context**

Was this working before/when did the issue start occurring?
happening for a few months, but most people have no conflict with cj4

Is this a problem in the vanilla unmodded game?
no

Discord username (if different from GitHub):
1samueleonard1#0001

**Comment by Watsi01** [comment]
I don't have the problem. Although I might not have the latest CJ4 WT....
Nope. I have the latest WT version (v0.10.2)

**Comment by patbuser** [comment]
Exactly same bug still there with latest A32NX dev build and latest WT CJ4 12.1.

**Comment by patbuser** [comment]
> Exactly same bug still there with latest A32NX dev build and latest WT CJ4 12.1.

correction, I just found it to be related to the WT G1000 mod rather than the CJ4. Removing G1000 fixes the issue. I also read on the WT discord, that it should be fixed when using the latest G1000 build. I didn't test though since I don't actually use the G1000.

**Comment by 2hwk** [comment]
Marked to be closed if there is no further update

**Comment by Samueleonard** [comment]
havent had the issue since the fork, anyone still having the issue can reopen or make a new issue but solved for me so i will close
