### ISSUE TITLE
Simbrief Username/Pilot ID Not Being Remembered Across Sessions On Tablet

### ISSUE THREAD

**Issue by MjrIncident** [flybywiresim/a32nx#4053]
**Mod Version**

A32NX Dev Version

**Describe the bug**

Simbrief username/ pilot id is not being remembered. Have to add every flight.

**To Reproduce**

1. Launch Tablet
2. Goto Company
3. 

**Expected behavior**

Expect stored ID/Username from last check. I see it is doing that for YT streamer EasyJetPilot... but not clear how this is achieved.

**Actual behavior**

Empty Field

**References**

**Additional context**

![image](https://user-images.githubusercontent.com/72098504/111913074-60c7c680-8a64-11eb-8c1f-5b634eadd7f7.png)

Was this working before/when did the issue start occurring?
I have seen it working on another users' screen.
Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
How do you shut down/close your simulator?

**Comment by MjrIncident** [comment]
Full parked switch off to dark - for sure, sometime after triggering the flight log conclusion page, I go to main menu and then close the program.

**Comment by ZigTag** [comment]
Fixed in efb ui rewrite

**Comment by MisterChocker** [comment]
#4053

**Comment by MjrIncident** [comment]
Fantastic :-)

**Comment by MisterChocker** [comment]
Keeping this open for tracking.

**Comment by bouveng** [comment]
I think this still is an issue. Username have never been saved for me.

**Comment by ZigTag** [comment]
> 
> 
> I think this still is an issue. Username have never been saved for me.

It's fixed in #4026

**Comment by wined2310** [comment]
not fixed for me.
I am on the current DEV version and the settings menu on the flyPAD does not provide a Simbrief username option like shown in #4026 
So I have to enter it each time I start the Sim.
Works fine on the MCDU, but not on the flyPad.

Do I have to update the flyPAD to V2 seperately?

**Comment by BjoernHund** [comment]
The Feature in PR #4026 is currently not merged in the dev version. It is still a feature. If it is complete, it will be merged to the dev version. So you have to wait. 

@ZigTag want's to say with his comment, that an already known issue and it is worked on it.
