### ISSUE TITLE
A320 Autopilot Issues

### ISSUE THREAD

**Issue by ZachW77** [flybywiresim/a32nx#5151]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-05-05T23:03:06+00:00",
  "ref": "v0.6.1",
  "sha": "4a1cccc90ab3997109e394402ab9b41a80fbf325",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Autopilot will be working great and all of a sudden a turn happens, and it never finishes out of a waypoint. Flight Director will just stay locked on a left turn and the only way to do anything is to get out of autopilot, press DIR TO [Waypoint Name] on MCDU and re-engage autopilot. While the auto-pilot is in this bugged state, almost nothing works, aircraft will not capture localizers either.

### Expected behavior

AUtopilot should be laterally following waypoints and either manually or automatically vertical guidance.

### Steps to reproduce

1) Fly into a STAR.
2) Try to arrive into via ILS runway at some major airport.

### Discord Username (optional)

TheGeneral#0773

**Comment by Benjozork** [comment]
Fixed in custom autopilot in dev build

**Comment by AdamNZ** [comment]
{
  "built": "2021-06-20T10:23:56+00:00",
  "ref": "master",
  "sha": "84964e339507e06694ff2e96bdda518824c85aa4",
  "actor": "MisterChocker",
  "event_name": "manual"
}

*Not fixed on my system* (latest DEV build). Basically (whilst in-flight) any edits to the currently loaded flightplan in the MCDU causes the A/P to lose the plot. Even after executing a DIR command, it still misbehaves.

**Comment by Benjozork** [comment]
That's an issue with the default flight plan system then, which is being replaced entirely.

**Comment by AdamNZ** [comment]
OK - great (thanks)! The odd thing is that it behaved a lot better a few builds ago (!!). I'll shaddap and wait until the new FP comes along ;)

**Comment by Benjozork** [comment]
This has not been touched for months, it's just random.
