### ISSUE TITLE
FlyPad shows "Leaflet" 

### ISSUE THREAD

**Issue by matze-tech** [flybywiresim/a32nx#5308]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-10T11:13:17+00:00",
  "ref": "master",
  "sha": "a33bbcf89fd5a011163eee22d6c0eb4a8af46796",
  "actor": "davidwalschots",
  "event_name": "manual"
}
```

### Describe the bug

When I zoom in, a Leatflet page comes up. When I zoom out again, the normal FlyPad comes back but I can't click anything.

### Expected behavior

The bug is also in the new flyPad.

### Steps to reproduce

Click on "Openstreetmap" at the bottom right of the map on the dasboard

 Then comes the "Leaflet" page.

### References (optional)

https://user-images.githubusercontent.com/60877083/125431040-3b285173-3144-40d6-954f-248701bd35ab.mp4

### Discord Username (optional)

matze[]# 2346

**Comment by MapleNAV-TCASFAULT** [comment]
Please update the dev version, FlyPadOS2 was released yesterday removing such bug

**Comment by 2hwk** [comment]
Closed as fixed in later build

**Comment by bouveng** [comment]
Still an issue in `master`. 
Will create a proper fix for this.
