### ISSUE TITLE
Pushback Begins Without Command

### ISSUE THREAD

**Issue by AviationSpotter** [flybywiresim/a32nx#5315]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-13T05:36:14+00:00",
  "ref": "master",
  "sha": "faee7a996a5c51708fc4ed76963d58b18bbb59a9",
  "actor": "2hwk",
  "event_name": "manual"
}
```

### Describe the bug

Pushback begins without command if not on the Ground page.

### Expected behavior

Pushback to only begin when command given.

### Steps to reproduce

1. Spawn C&D
2. Use EFB and call a tug
3. Right after calling a pushback navigate and remain to another page

### References (optional)

https://user-images.githubusercontent.com/72807945/125545082-a94ae74b-b98c-44bf-9194-d3e164d2612f.mp4

### Discord Username (optional)

Aviation Spotter#9102

**Comment by enriqueo62** [comment]
If you are using the new PUSHBACK mod in the Toolbar, It gets activated when the APU starts and becomes available. SO, I believe it is not related to the A320NX

**Comment by enriqueo62** [comment]
Okay. Sorry, I just saw the video.

**Comment by MjrIncident** [comment]
I use ai checklist completion - think it is this that causes the tug to begin without command from elsewhere. ? Not certain though.

**Comment by AviationSpotter** [comment]
Okay everyone, if you would like to investigate further in this issue then please read "Steps to reproduce" and "References". Thanks!

**Comment by kiemdoder** [comment]
I could reproduce this bug and  will fix it. Just give me some time though since I'm totally new to this project.

**Comment by kiemdoder** [comment]
I think someone fixed this already. After trying to find the bug in the development browser version of the EFB I could not find anything wrong and then stared to suspect that maybe the bug has been fixed. I just installed the latest development version of the mod and I can't reproduce the bug there any more.

@AviationSpotter can you maybe confirm that the bug is fixed now?

**Comment by AviationSpotter** [comment]
> I think someone fixed this already. After trying to find the bug in the development browser version of the EFB I could not find anything wrong and then stared to suspect that maybe the bug has been fixed. I just installed the latest development version of the mod and I can't reproduce the bug there any more.
> 
> @AviationSpotter can you maybe confirm that the bug is fixed now?

Sure! I'll test and leave another message about my findings when I can.

**Comment by AviationSpotter** [comment]
> > I think someone fixed this already. After trying to find the bug in the development browser version of the EFB I could not find anything wrong and then stared to suspect that maybe the bug has been fixed. I just installed the latest development version of the mod and I can't reproduce the bug there any more.
> > @AviationSpotter can you maybe confirm that the bug is fixed now?
> 
> Sure! I'll test and leave another message about my findings when I can.

@kiemdoder I am still reproducing this bug on the latest development branch.

**Comment by Ramsay58** [comment]
Just to confirm, you don't have AI co-pilot coms enabled ?

There's a (old?) bug where, with

• Options > Assistance Options > Piloting ---> AI Radio Communications (ATC) = ON
![20210803012957_1](https://user-images.githubusercontent.com/31033413/127941445-74487f71-78a0-48d4-bbb9-8ece37689183.jpg)

... the AI Co-pilot calls for (and gets) push back when the FlyByWire APU spools up to 100%
![20210803013839_1](https://user-images.githubusercontent.com/31033413/127941508-1001afac-a9dd-49d4-ad78-527ceda86f42.jpg)
 
SU5 reset some of my default settings and this was one of them.

Tested using latest SU5 and Dev Build

"built": "2021-08-02T11:41:34+00:00",
  "ref": "master",
  "sha": "89dcbdd03c19a917a3f45ebab0ab518ebee7f588",
  "actor": "sidnov",
  "event_name": "manual"

**Comment by NUTTTTTTTT** [comment]
Was able to reproduce following process shown in video.

**Comment by Ramsay58** [comment]
Same.

> Steps to reproduce
1. Spawn C&D
2. Use EFB and call a pushback
3. Right after calling a pushback navigate and remain to another page

**Comment by kiemdoder** [comment]
I found the problem in the code. There is a variable in the sim that needs to be set periodically when we call the tug but does not want it to move the plane yet. The code that periodically sets this sim variable stops when another page is selected to be displayed in the EFB.

I will create a PR once I've thought of a way to fix the problem without making a mess of the code.
