### ISSUE TITLE
Option to disable Flight Display Pixelization

### ISSUE THREAD

**Issue by Croniac** [flybywiresim/a32nx#5424]
### Aircraft Version

Development

### Description

While the new pixelization looks great on screen, in VR it creates a bad moire effect that makes the screens hard to read unless zoomed in close.

Please consider an option to disable this feature as it renders the cockpit very uncomfortable to use.

### Discord Username (optional)

Croniac

**Comment by SierraBravo1** [comment]
This issue is not only related to VR. I have the moiré effect also on my screen (1080p).
Please add an option to disable it.
It looks poor:
![grafik](https://user-images.githubusercontent.com/76132388/127289032-c066d71f-ca54-417e-826c-a453e0199668.png)

**Comment by bouveng** [comment]
Hi! This is being looked at, in various forms.
I think the impl. will work so that the pixels are only visible when watching/zooming really close to the screens.

**Comment by TLSY2** [comment]
same issue here, not only on VR!

**Comment by daddyali** [comment]
![image](https://user-images.githubusercontent.com/6809626/127452556-64566b84-6245-4756-9a9b-7f41f6f502df.png)
 Ditto on 1080p - showing the 'popped out' version too which looks even worse. Definitely would appreciate a 'turn it off' option please.

**Comment by TLSY2** [comment]
maybe not completely off, it isnt even realistic as it looks now.

**Comment by cloudynetwork** [comment]
It looks great for me. I only notice any form of pixels when zoomed right in and certainly don't get the kind of things being posted here. What's the difference? Are you running non-native resolutions or something?

**Comment by TLSY2** [comment]
> It looks great for me. I only notice any form of pixels when zoomed right in and certainly don't get the kind of things being posted here. What's the difference? Are you running non-native resolutions or something? 

If youve got a nasa pc then you dont see, but us who cant read it by not even zooming out more than deafault is a pain!

**Comment by daddyali** [comment]
The work done on https://github.com/flybywiresim/a32nx/pull/5483 has massively improved this for me - in fact, it's no longer an issue at all. I now only see the pixels when I effectively have my virtual nose up against the screen in question. In normal use, pop-up use, even head forward the screens are back to being crisp with no artifacts. Great work from @2hwk

**Comment by tracernz** [comment]
> It looks great for me. I only notice any form of pixels when zoomed right in and certainly don't get the kind of things being posted here. What's the difference? Are you running non-native resolutions or something?

The issue was fixed the day before.

**Comment by tracernz** [comment]
Let’s close this since the issue is fixed.

**Comment by TLSY2** [comment]
I still have issues, it still looks like pixelated from far away but less!

**Comment by davidwalschots** [comment]
@TLSY2 could you provide screenshots?

**Comment by tracernz** [comment]
> I still have issues, it still looks like pixelated from far away but less!

Pixelated or blurry? What's your render scaling settings? The pixelation no longer happens unless you're very close so it's not likely to be that unless you're running an older build.

**Comment by TLSY2** [comment]
> > I still have issues, it still looks like pixelated from far away but less!
> 
> 
> 
> Pixelated or blurry? What's your render scaling settings? The pixelation no longer happens unless you're very close so it's not likely to be that unless you're running an older build.

To be honest i dont even know! I play at high fov, render settings are ultra, anti aliasing Taa... But before the pixelisation of the screens it was more clear. I will provide screenshots later.

**Comment by MisterChocker** [comment]
Closing since issue seems to be resolved.

**Comment by TLSY2** [comment]
> Closing since issue seems to be resolved.

How do you see it solved? The title is option to disable it.

Maybe add in efb to turn it off.
