### ISSUE TITLE
Crash when loading into Airport

### ISSUE THREAD

**Issue by JRascagneres** [flybywiresim/a32nx#5446]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-07-29T00:29:16+00:00",
  "ref": "master",
  "sha": "7068cb5f6aa73badf20867b3fcfe2077e9e65004",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Loaded into airport VHHH and get a CTD as soon as I click 'ready to fly'.
Note: Other planes load fine.

### Expected behavior

Don't expect a CTD

### Steps to reproduce

1. Select A32NX as aircraft
2. Load into VHHH

### Discord Username (optional)

Scorp#3465

**Comment by delta5150** [comment]
CTD when loading at KDEN c/d at gate a34. Other planes load good.

**Comment by avielmenter** [comment]
I seem to be experiencing this issue with the dev version and the stable version. I've tried loading the stable one at RJTT and KSFO, and the dev one at RJTT. CTD either before loading is complete or seconds after.

**Comment by aguther** [comment]
With development version loaded into:
- VHHH :heavy_check_mark:
- KDEN Gate A34 :heavy_check_mark:
- RJTT
- KSFO

Please follow the guide CTD Resolution and try again:
https://docs.flybywiresim.com/start/reported-issues/#ctd-resolution

If you have been using the stable version from marketplace, ensure you're uninstalling the stable version in the content manager.

**Comment by avielmenter** [comment]
Thank you for the advice. I tried the steps linked above and though I still have more testing I want to do, the one that seems to have done the trick is deleting my rolling cache.

**Comment by aguther** [comment]
Hmm, can you please try the following:

1. Restart your sim and wait until in the main menu
2. Go to options -> general options -> developer -> enable dev mode
3. In menu „Options“ on top of screen enable option „Fast WASM compilation“
4. Go to the folder, depending on the version you have; MS Store: `%LOCALAPPDATA%\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\flybywire-aircraft-a320-neo\`, Steam: `%APPDATA%\Microsoft Flight Simulator\Packages\flybywire-aircraft-a320-neo\`
5. In that folder delete files starting with m* (*.dll, *.cache, *.lib, *.natvis, *.pdb)
6. Switch to MSFS again
7. Start a flight with A32NX (at best on the runway)
8. When flight is loaded and plane is working you can exit dev mode again

**Comment by aguther** [comment]
Please also ensure you‘re not using any overclocking etc.

**Comment by LanJack** [comment]
Crashes when loading into ZGGG-ZABD Dev version

**Comment by Saschl** [comment]
Did you try the steps mentioned by Aguther above?

**Comment by 2hwk** [comment]
Rolling up and consolidating loading in CTDs into this issue.

**Comment by bbrks** [comment]
I CTD'd in dev version VHHH when this issue was filed too. Could spawn fine in NZQN, and also back in VHHH with vanilla a320.

**Comment by Benjozork** [comment]
Please provide the scenery / lack thereof when mentioning an airport.

**Comment by bbrks** [comment]
No scenery. Community folder removed. All world updates installed.

**Comment by aguther** [comment]
- my steps from above executed?
- any overclocking of the PC in place?

**Comment by aguther** [comment]
Right now to me it seems that it‘s an issue on MSFS side but maybe we find something that triggers the issues. I was spawning into those airports without any issues, so there must be some difference somehow. We have unfortunately no way to analyze anything that might cause the issue on our end (if so), because MSFS lacks support of it.

**Comment by JRascagneres** [comment]
Yeah its an interesting one... For @bbrks and I (and a couple people on discord, and above) there seems to be some correlation between VHHH (and clearly others) and the A32NX. 
A32NX seems to work fine at a few other airports I tried and other aircraft work fine in VHHH.
I also carried out the actions noted by @aguther with the full clean re-install and the WASM dev options.

**Comment by aguther** [comment]
Yeah, but I also spawned into VHHH without issues…

**Comment by JRascagneres** [comment]
@aguther In the airports that do work I do seem to have long stutters which is kinda making the sim unplayable for now. Perhaps other people who crash see similar? Could be some connection there too...

Performance is great but appears the stability has regressed quite a lot...

**Comment by globin** [comment]
Have you got any issues with USB input devices? Long stutters and occasional CTDs occur when they dis-/connect. Try disconnecting as much as possible, I have noticed this too with a keyboard that has issues with its cable.

**Comment by gb09f** [comment]
I can spawn OK at VHHH once I remove Navigraph.  with Navigraph in Community, I get a CTD.

**Comment by JRascagneres** [comment]
I had no items in community other than a32nx

**Comment by gb09f** [comment]
Re-added Navigraph and now no CTD at VHHH. Weirdly intermittent.

**Comment by aguther** [comment]
I also have Navigraph, but that brings me to an idea. Can you try to close the sim and delete the Content.xml and then open the sim again. Sometimes it seems the order of packages is getting an issue.

**Comment by JRascagneres** [comment]
@aguther Can give it a go tonight, although I have no other community items at the moment?
Where is the Content.xml file if you think it might help?

**Comment by aguther** [comment]
@JRascagneres When I‘m at home I can check the folder, maybe do a backup. The file contains all scenery that are in the sim, including base data and all the add-on airports coming with MSFS itself (i.e. World Updates).

**Comment by ErickSharp** [comment]
I am not 100% sure if it's what causes this issue, but larger airports definitely seem to aggravate the issue.

**Comment by navtek** [comment]
I was also having the same issue when I was loading KATL, it would crash once I was 'Ready to fly', I was able to fix it by deleting the rolling cache and also removing the Asobo A32NX, after that I was able to do a round trip from KATL - KCLT - KATL without any issues, not sure if this will work for other, but work giving it a try

**Comment by JRascagneres** [comment]
> @JRascagneres When I‘m at home I can check the folder, maybe do a backup. The file contains all scenery that are in the sim, including base data and all the add-on airports coming with MSFS itself (i.e. World Updates).
> 
> Edit:
> Found something in the Navigraph forums:
> [forum.navigraph.com/t/faq-uninstall-the-navdata-revert-back-to-the-stock-data/4853](https://forum.navigraph.com/t/faq-uninstall-the-navdata-revert-back-to-the-stock-data/4853)
> [forum.navigraph.com/t/faq-location-path-of-content-xml-package-file/2798](https://forum.navigraph.com/t/faq-location-path-of-content-xml-package-file/2798)

I'll give it a try, like I said I removed other community items but possible something stuck around I guess

**Comment by speedbird5** [comment]
Same problem here at EGKK and EGLL trying to load at any gate.
Can load on runway with engines running at both EGKK and EGLL no problem.
Have tried deleting rolling cache and deleting Asobo A320 but no joy.

**Comment by CBGonzalez** [comment]
Had the same CTD immediately after pressing "Ready to fly" at several different airports. **WORKAROUND: WAIT UNTIL AIRCRAFT FULLY LOADS** before pressing "Ready to fly" (to me that means waiting until the aircraft data appears on the lower left). Curious to see if this works for others

**Comment by aguther** [comment]
It’s really frustrating…especially because we have so few possibilities to find out what is going on and what is the cause.

Keep it coming and please try to proactively share as much info as possible.

**Comment by ErickSharp** [comment]
For those that have issues with CTD's when loading into large airports:

If you have developer mode enabled, select a small general aviation aircraft and spawn into the airport with it, from there you can go to Aircraft Selector and search for 'flybywire' and select the A32NX. This seems like a decent workaround for now.

**Comment by aguther** [comment]
@speedbird5 Tried both EGKK and EGLL in C&D and no CTD.

**Comment by aguther** [comment]
Now I have an idea...I must admit, I'm flying with the cfpm version...will try with the latest dev now.

**Comment by jcastilloalonso** [comment]
Having this issue loading in gate 31 on KDFW airport. All other airplanes work correctly but a32nx results in FS crashing. Please let me know if there's anything I can do to troubleshoot further, but so far tried everything and ends up crashing.

Unrelated to a32nx but FS2020 is also crashing when loading with my Thrustmaster Airbus Officer pack is plugged in and freeze right away when I plug it in when sim is running, so wonder if this is also affecting people with certain configurations where FS2020 is just unstable.

**Comment by aguther** [comment]
@jcastilloalonso Have you tried all suggestions from this issue?

The freezing is "normal" since beginning when you plug-in or remove devices, I have this often when I switch from Desktop to Laptop with my KVM switch or vice versa. Usually it repairs after 30 s or so.

**Comment by jcastilloalonso** [comment]
@aguther Yes tried the rolling cache, clean a32nx install, no other mods and yesterday actually uninstalled everything and started clean (left download overnight) same replicable results. Today test was fresh install, update everything, install latest Dev release using installer, select a32nx, select departure KDFW gate d31 and press start. Loads normally, get the ready to fly screen, press it, cockpit launches and CDT. AI airplanes are turned off as I also read they might interfere.

I used to have the "usual" 30s freeze when plugging them in, but now it's a hard freeze, have to kill FS2020 on the task manager as it won't respond even after 10 minutes. Also after this I have to terminate and repair FS2020 multiple times for it to eventually stop the CTD during the first loading screen and the stick/throttle unplugged. After I manage it to start, if I plug them with FS2020 closed and start it, the CTD during load returns. So there's definitely something happening there (opened a Zen ticket with Asobo for this)

**Comment by aguther** [comment]
Hmm...annoying 😒

**Comment by xjanat** [comment]
I have same experience at LKKV and LKPR , everything work fine until take off  - than comes crash to desktop.  When I have used stable version, sim has crashed also when was FBW A320 used as AI airplane .  I have tested Project Airbus A321, Bredok 737, Captain 777 and also standard default A320 Neo, all planes are working only when is FBW completely uninstalled :/

**Comment by aguther** [comment]
What I have enabled is that generic planes are used for multiplayer and AI.

**Comment by xjanat** [comment]
I´m using Russian live traffic + generic planes are used also as AI.  Strange is that todays morning was development version fine, than comes a few updates ... :/

**Comment by aguther** [comment]
What is Russian live traffic?

Well it’s not that those changes you mentioned are really causing the issues. It’s the sim that seems to have issues with them.

So let’s not get into that discussion again as in the other issue. We are all doing this in our free time running behind a lot of stuff we have not caused. so I ask you to respect that.

**Comment by xjanat** [comment]
Russian Live traffic system RLTS , very good traffic addon.  Point of previous message is not negative, just only thing for help..something was happend during todays update , morning version was fine. Please do not take it as negative, just as point. Thank you for your help and croos fingers :)

**Comment by sidnov** [comment]
FYI: Russian Live Traffic is a bunch of poorly compiled AI traffic models "stolen" from various other sources, both free and paid. Let's not get any deeper as to how "good" it is because it could very well be a cause of issues. As far as the A32NX is concerned, we'll wait for the hotfix to release instead of making unnecessary changes to the aircraft.

**Comment by JRascagneres** [comment]
> we'll wait for the hotfix to release

@sidnov Has this been confirmed or are we just presuming?

**Comment by navtek** [comment]
> > we'll wait for the hotfix to release
> 
> @sidnov Has this been confirmed or are we just presuming?

This has been confirmed
https://forums.flightsimulator.com/t/asobo-working-on-a-hotfix-for-ctds/429841

**Comment by JRascagneres** [comment]
I mean I can't even start the game now soo.... Thats great

**Comment by navtek** [comment]
Confirmed: update coming out tomorrow at 8am PT 
https://www.flightsimulator.com/july-29th-2021-development-update/

**Comment by sidnov** [comment]
@JRascagneres Navtek has the news! :)

**Comment by JRascagneres** [comment]
Thanks.

**Comment by JRascagneres** [comment]
So... Managed to fix crash on load by removing process lasso...

**Comment by JRascagneres** [comment]
> @JRascagneres When I‘m at home I can check the folder, maybe do a backup. The file contains all scenery that are in the sim, including base data and all the add-on airports coming with MSFS itself (i.e. World Updates).
> 
> Edit:
> Found something in the Navigraph forums:
> [forum.navigraph.com/t/faq-uninstall-the-navdata-revert-back-to-the-stock-data/4853](https://forum.navigraph.com/t/faq-uninstall-the-navdata-revert-back-to-the-stock-data/4853)
> [forum.navigraph.com/t/faq-location-path-of-content-xml-package-file/2798](https://forum.navigraph.com/t/faq-location-path-of-content-xml-package-file/2798)

You sir are a god. This fixed it... Guessing xml had stuff around from before I removed the items from community

**Comment by nicbet** [comment]
> Hmm, can you please try the following:
> 
> 1. Restart your sim and wait until in the main menu
> 2. Go to options -> general options -> developer -> enable dev mode
> 3. In menu „Options“ on top of screen enable option „Fast WASM compilation“
> 4. Go to the folder, depending on the version you have; MS Store: `%LOCALAPPDATA%\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\flybywire-aircraft-a320-neo\`, Steam: `%APPDATA%\Microsoft Flight Simulator\Packages\flybywire-aircraft-a320-neo\`
> 5. In that folder delete files starting with m* (*.dll, *.cache, *.lib, *.natvis, *.pdb), see also ![](https://camo.githubusercontent.com/b5acc8ed43ecb9bddd4dbb787bc907e954c38cccc21cc0721286d373b179b69c/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3833383036323732393339383937363532322f3836393733363639303639353137323135362f756e6b6e6f776e2e706e67)
> 6. Switch to MSFS again
> 7. Start a flight with A32NX (at best on the runway)
> 8. When flight is loaded and plane is working you can exit dev mode again

Had the same issue, FBW A32NX mod (development version) crashing half way through loading bar after SU5, was working fine in SU4 probably my most flown aircraft with hundreds of hours.

Turns out, that somehow the two folders"
- `AppData\Roaming\Microsoft Flight Simulator\Packages\flybywire-aircraft-a320-neo`
- `AppData\Roaming\Microsoft Flight Simulator\Packages\flybywire-aircraft-a320-neo\work`

were entirely missing after my clean install (and clean install of the FBW Mod via the FBW Installer).

I manually created these folders, and also removed the AppData\Roaming\Microsoft Flight Simulator\SimObjects\FlyByWire_A320_NEO\state.CFG file and no more CTDs :wink:

**Comment by tgupta3** [comment]
For me CTD went away by disabling AI traffic. Before that I would usually get one in 10-15 minutes after loading into the airport.

**Comment by speedbird5** [comment]
> Had the same CTD immediately after pressing "Ready to fly" at several different airports. **WORKAROUND: WAIT UNTIL AIRCRAFT FULLY LOADS** before pressing "Ready to fly" (to me that means waiting until the aircraft data appears on the lower left). Curious to see if this works for others

Yes !!! This is the temporary fix.  Thankyou

**Comment by speedbird5** [comment]
After Hotfix to SU5 - 1.18.14.0 now cannot load FBW A32NX either at gate or on runway at EGLL.
CTD immediately on load of aircraft even before pressing fly.
Previously could load on runwway but not now.
Am using version below.
Temporary workaround is load Cessna 152 on runway and then load A32NX using developer mode.
{
  "built": "2021-07-30T14:00:27+00:00",
  "ref": "master",
  "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
  "actor": "davidwalschots",
  "event_name": "manual"
}

**Comment by Dites33** [comment]
> After Hotfix to SU5 - 1.18.14.0 now cannot load FBW A32NX either at gate or on runway at EGLL.
> CTD immediately on load of aircraft even before pressing fly.
> Previously could load on runwway but not now.
> Am using version below.
> Temporary workaround is load Cessna 152 on runway and then load A32NX using developer mode.
> {
> "built": "2021-07-30T14:00:27+00:00",
> "ref": "master",
> "sha": "5668670c9fdcd56a31b2a46c95272013fb65e013",
> "actor": "davidwalschots",
> "event_name": "manual"
> }

same error at LFPG but some times works for several minutes and crash, workaround works,

**Comment by aguther** [comment]
I’m really sorry for the problems, but it’s out of our control.

**Comment by Dites33** [comment]
really, we must wait ASOBO fix ? no problem :)

**Comment by aguther** [comment]
Yeah it’s really a problem of the sim…

**Comment by Captherky** [comment]
Evan after Asobo patch to update 5, FBW Airbus CTD when trying to load flight. Can not fly the FBW Airbus in any version, even the Marketplace download?

**Comment by aguther** [comment]
Ensure you have uninstalled the marketplace version in the content manager.

**Comment by Captherky** [comment]
Thanks, yes I just did this.

Do any versions actually work or is there a problem with FBW installed into the community folder?

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aguther** [comment]
@Captherky I recommend installing the latest development version with the FBW installer. At least for me it works without any CTD.

**Comment by aguther** [comment]
Any other experiences since the hotfix?

**Comment by Captherky** [comment]
Cessna floatplane is horrible!
Wheels don’t retract after runway take off making water landing silly.
Water rudders don’t deploy, water rudder effectiveness is poor.
Inertia from those big floats is not apparent!

Aerosoft CRJ HUD is not retractable. CRJ doesn’t track FMC plan (Aerosoft aware and trying to fix with a patch, but Germanic efficiency means this could take weeks!)

Only aircraft that has been updated and works well is CJ4!

Bit of a mess really…do they ever test this stuff, before pumping it out?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jcastilloalonso** [comment]
> Any other experiences since the hotfix?

Been playing all morning to try and identify exactly what helps and what causes the CTD. This looks like a Asobo bug. Using low quality settings seems to help. I'm successful to start flight in runway like 80% of the time if I have graphic quality in low and let the ready to fly screen stay until airplane comes into picture. Then I do notice screens start black and take like 5-10s to load and everything works fine. Using graphics in medium decreases the chance of successful load to less than 10%. Once everything is loaded, I can switch back to high settings and simulator will work great.

If I start cold and dark, 90% of the time FS2020 will crash during loading before ready to fly screen. other 10% will show aircraft and crash when pressing ready to fly.

Using Asobo airplanes works fine both in cold and dark and spawning in runway. So I guess the extra complexity of the a32nx is what is at fault (maybe Asobo limited preloading of airplane systems to try and optimize for XBOX?) this is because included airplanes are working fine.

Simulator is still very unstable for me, crashing when changing screen and still unable to start it with controllers plugged in USB. I have to launch simulator, spawn and then connect controllers for it to work and not crash. Because of all this, I find it very difficult to troubleshoot and identify issues when we are not sure if a32nx is causing the issue or just a simulator CTD issue.

I'm available to do any troubleshooting or extract any logs etc. if possible and interest.

Thanks for all your work and time in this mod. Can't wait to fly again!

**Comment by aguther** [comment]
I think I can speak for most if not all Devs from FBW and can tell you we are as frustrated as many of you.

It would be much easier if the error is on our side, it would be easier to fix.

What I can tell you from my own experience as a last way: I had also many CTD some time ago and it got a lot better when I disabled all overclocking I had and even disabled XMP in the BIOS. But might be very specific to my case…

**Comment by jcastilloalonso** [comment]
> I think I can speak for most if not all Devs from FBW and can tell you we are as frustrated as many of you.
> 
> It would be better if the error is on our side, it would be easier to fix.
> 
> What I can tell you from my own experience as a last way: I had also many CTD some time ago and it got a lot better when I disabled all overclocking I had and even disabled XMP in the BIOS. But might be very specific to my case…

Thanks! a lot and I agree. I'm using a laptop so no overclocking or anything in particular. Been using the same for a while and actually just cleaned the fans and inside yesterday just to be sure.

If there's anything I can do to help troubleshoot I have some technical background and can download particular builds to test and report findings.

Like I already said though, I think SU5 is too unstable to try and pinpoint exactly what else is a32nx adding to the mix that makes it more unstable.

**Comment by Captherky** [comment]
OK
I have close dev contact with MCE. Multi Crew Experience.
I do Videos for them and assist in development of First Officer Comms.

I am a ATPL expert and wish to see ATPL aircraft in this sim . As we have in P3d.
PMDG , QW etc…

I only have the Aerosoft CRJ as my primary ATPL platform, the Asobo ATPL aircraft are not good. Should  have grabbed the Quality Wings Team at the start..this is the best simulation platform aircraft of all time…JUMP AHEAD..feature is superb!

I also commend the CJ4 team for their efforts, the CJ4 is excellent in U5 Patch+1. All works superbly!

I don’t O/C I have a purchased machine from Scan UK..3XS, so its standard fare!

The only thing I can commend Asobo on is the increased smoothness and weather.

I set 30 FPS with VSynch on and its super smooth at WQHD levels.
My PC is mid range with RTX 2070, so nothing special.

The failure of FBW is no shock to me. They were doomed to failure from the start.
100’s of coders (ALL Armature) working on the thing! UG HORRID.

Lets hope PMDG don’t pull out!

Best Regards
David



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by delta5150** [comment]
I just tested after updating SU5 fix and dev version of FBW. Loaded C/D at gate A26 KDEN. No problems. I have not performed power up and start up yet. I will do that later and let you know. Gonna fly KDEN-KSAN.
    On Friday, July 30, 2021, 01:15:46 PM PDT, jcastilloalonso ***@***.***> wrote:  
 
 



I think I can speak for most if not all Devs from FBW and can tell you we are as frustrated as many of you.

It would be better if the error is on our side, it would be easier to fix.

What I can tell you from my own experience as a last way: I had also many CTD some time ago and it got a lot better when I disabled all overclocking I had and even disabled XMP in the BIOS. But might be very specific to my case…


Thanks! a lot and I agree. I'm using a laptop so no overclocking or anything in particular. Been using the same for a while and actually just cleaned the fans and inside yesterday just to be sure.

If there's anything I can do to help troubleshoot I have some technical background and can download particular builds to test and report findings.

Like I already said though, I think SU5 is too unstable to try and pinpoint exactly what else is a32nx adding to the mix that makes it more unstable.

**Comment by 2hwk** [comment]
Please stay laser focused and on topic, this is an issue, not a discussion. Only information that will help with mapping out CTD issues. Else the thread will be locked out.

**Comment by Benjozork** [comment]
@Captherky Please stop the unprofessional and off-topic comments immediately or you will be banned from discussing here.

**Comment by aguther** [comment]
@Captherky I do not agree to what you say.

It’s very offensive to all call us amateurs without knowing what we do in real life. So mind your words.

The issues are not caused by the A32NX they are caused by the sim. We have some information about a few things going with wasm compilation that „just“ have been changed without upfront information. It seems a compiler option is now active by default that has a huge negative impact on math calculations. Now sure it’s FBW fault…

**Comment by Captherky** [comment]
OK fair enough.

Absolutely no offense intended to you or your team.

Don’t be so sensitive. Take it as a compliment my friend!

I don’t want to download programs that CTD! Neither do anyone else!

Lets get it right!

Asobo are releasing untried , untested software.

I will be uninstalling this stuff if it continues!

My P3d is far more satisfying with programs like GSX 2!!

The Asobo ground vehicles is a complete mess!

Loading when unloading…vehicles crashing into each other ..its a mess!

The only pluss is the pretty graphics.

Flying for real is a no go!

Best regards





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by 2hwk** [comment]
For now, information related to CTDs can be posted in the #Crash To Desktop thread in the support channel of the discord. This will be opened after a cooling off period.

Apologies to those with on-topic concerns related to this issue.

**Comment by Benjozork** [comment]
"Take it as a compliment" "You are all amateurs and doomed to fail" seriously man ?

Anyway, what @2hwk said.

**Comment by 2hwk** [comment]
Note: If you are having repeated CTDs, please run ``DISM /Online /Cleanup-Image /RestoreHealth`` and ``sfc /scannow`` in the Powershell (Admin) Window. Right click the Start Menu button and select Windows Powershell (Admin).

**Comment by bohryss** [comment]
I have the same problem on LFLL: Start a flight in cold and dark in a gate then CTD after click on ready button.

**Comment by yannTravel** [comment]
I have the same problem too !

**Comment by Benjozork** [comment]
At this point I would wait for hotfixes from Asobo.

**Comment by delta5150** [comment]
I completed a flight from KEWR - KLAS yesterday starting C/D at gate c84. Flight went very well. Had some weather issues using live weather so I switched to a different weather in the sim then switched back later. Wanted to do a auto land ILS to 26L at KLAS but the localizer was WAY off. Hand flew the approach. Aircraft performed very well. I've been saving the successful FBW updates so I can revert back if a update CTD.

**Comment by Seth-Dark** [comment]
I had also those crashes while loading an airport with A32NX. 
The only option that worked ( at least on my setup):
After SU5 when you enter on MSFS world map and have a different aircraft and change to A32NX i had ctd when loading an airport.
the only way to avoid those crashes was to have A32X as my main Aircraft when MSFS is loaded.
weird issue....

**Comment by Onkel-Benz** [comment]
Had same issue regarding CTD using the FBW A32NX when ready to fly screen hatched.
Solution found yesterday to equal the memory frequency of my 4x8GB DDR3-2400 GSKILL modules. 
Setting the memory clock in the BIOS down to 2200MHz and FS2020 returned to stable operation. Also verified by returning to 2400MHz, where again the same CTDs re-occurred. 
Also removed the feature of automated overclocking of my CPU. 

Previously also a problem with the latest NVidia driver was present. Downgrading to the 466.77 solved this side-issue for my 1070 card.

**Comment by ACSoft47** [comment]
For me, when building my flight, if I change the aircraft to the A32NX from any other aircrafts, I will have a systematic CTD, when I try to load my flight. When I start again, just after or even later on for other subsequent MSFS play sessions, as far as the A32NX is the active aircraft, any flight I will prepare and even if I change for another aircrafts, will NEVER CTD.

**Comment by aguther** [comment]
Can please provide at least the version you are using?

**Comment by ACSoft47** [comment]
DEV version downloaded the 2021.08.03.
What I described occur since PU5 and remain unchanged after both hotfixes.

**Comment by aguther** [comment]
Ok, please update to latest version there was a fix merged in the meantime that potentially fixes your issues.

**Comment by ACSoft47** [comment]
Ok, thanks, will do tomorrow and report here, if it solved or not.

**Comment by ACSoft47** [comment]
Just tested now the A32NX version: 2021-08-09T04:50:23+00:00 and the problem DIDN'T OCCURED. So it is great !
As you thought, the fix merged you talk me about, effectively solved this problem.
Thanks again for your help.

**Comment by sidnov** [comment]
CTDs have been mitigated with subsequent sim-updates. Re-open a new Github issue if required with updated details if CTDs still persist
