### ISSUE TITLE
Flypad not importing from simbrief

### ISSUE THREAD

**Issue by CapJambo** [flybywiresim/a32nx#5639]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-13T13:42:13+00:00",
  "ref": "master",
  "sha": "ea667a2b748d1d1ae4f917202706239ae4c126bc",
  "actor": "MisterChocker",
  "event_name": "manual"
}
```

### Describe the bug

Flypad does not import from simbrief. However, I can still import into MCDU from simbrief.
None of the options, Import from simbrief or Link to MCDU work, even though the MCDU is loaded with correct data from simbrief!
Cheers

### Expected behavior

Flypad load data from simbrief or MCDU

### Steps to reproduce

1-Turn on flypad
2-Import from simbrief
3-Nothing happens
4-power up
5-MCDU menu
6-ATSU
7-AOC menu
8-INIT/PRES
9-INIT DATA REQ*
10-Data imported from simbrief!

### References (optional)

<img width="1280" alt="Microsoft Flight Simulator Screenshot 2021 08 13 - 18 26 43 87" src="https://user-images.githubusercontent.com/88090584/129397065-5659256f-1a43-4717-a04d-a398a020107a.png">

### Additional info (optional)

That screeshot shows the flypad empty of data but the MCDU is loaded with simbrief's data!
I can see the Navigraph charts on the flypad though!

**Comment by CapJambo** [comment]
<img width="1280" alt="Microsoft Flight Simulator Screenshot 2021 08 13 - 18 56 46 85" src="https://user-images.githubusercontent.com/88090584/129400141-3063d34c-7197-421f-a349-bfc0f06fc79f.png">
Charts on flypad from navigraph

**Comment by Paytheon** [comment]
I'm experiencing this same exact issue. SIMBRIEF flight plan doesn't load. Also, my navigraph Charts load only "intermittently". In other words, they loaded earlier from KLAX to KSEA. But from KSEA to KORD they did not load in the flypad Navigation & Charts page at all.

**Comment by Paytheon** [comment]
I downloaded the latest Development pull and confirm this bug is fixed. Great job and thank you very much.

**Comment by CapJambo** [comment]
I still can't import from simbrief into flypad. Navigraph airport info is intermitent as you say. I have installer which has updated almost daily. I have re-installed the aircraft and strangely enough, I did not have to fill the simbrief with my username nor did I have to on the MCDU menu options for simbrief. How do we reset these, so I have to fill it up again. I feel that this might be my problem!
Cheers

**Comment by ErickSharp** [comment]
> I still can't import from simbrief into flypad. Navigraph airport info is intermitent as you say. I have installer which has updated almost daily. I have re-installed the aircraft and strangely enough, I did not have to fill the simbrief with my username nor did I have to on the MCDU menu options for simbrief. How do we reset these, so I have to fill it up again. I feel that this might be my problem!
> Cheers

EFB Settings page accessible through the gear icon on the bottom left!

**Comment by christianparpart** [comment]
> ### Aircraft Version
> 
> Development

I'm using "Stable" branch via the official installer, and I couldn't get the flypad to load my simbrief data either (but loading flightplan via MCDU from simbrief does work).

**Comment by mauryp** [comment]
I have the same issue: FBW Development version **Flypad** fails to connect to **Simbrief** although flight plan loads in FMS from Simbrief as expected. I noticed this issue has been reported to FBW Support some weeks ago but so far there's been no response from FBW. Is the problem being investigated? Or is there a (non-obvious) work-around?

**Comment by Benjozork** [comment]
Have any of you set your simbrief username **both** in the flypad and in the MCDU ? They are not linked at the moment.

**Comment by Saschl** [comment]
Did you enter your simbrief username in the settings? Unfortunately it needs to be configured both in the mcdu and Flypad to work correctly

**Comment by mauryp** [comment]
Yes; my Simbrief ID appears in both the MCDU and flypad.

**Comment by Benjozork** [comment]
Do you use LIDO format ?

**Comment by mauryp** [comment]
Yes, LIDO format

**Comment by tracernz** [comment]
> 
> 
> Yes; my Simbrief ID appears in both the MCDU and flypad.

The flypad does not accept IDs, only usernames.

**Comment by CapJambo** [comment]
Thing is, I did not change a thing and it does not work, the FLYPAD. Flight
Data can be imported from simbrief directly to MCDU. Maybe it has always
been like this, I don't know. And the most strange thing is that if I
delete A32NX completely from the sim and reinstall it, already the simbrief
details are filled in, which is strange to say the least. If we wanted to
change the login for any reason I don't have an idea on how to do that and
just maybe that is what the problem is.

**Comment by mauryp** [comment]
#The flypad does not use IDs, only usernames.
That was the problem (Who new?)
Thanks for pointing out the anomaly and its workaround to a most frustrating issue.

**Comment by Benjozork** [comment]
Oops..

Someone is working on fixing that, actually. Sorry for the inconvenience.

**Comment by MisterChocker** [comment]
Closing since issue resolved https://github.com/flybywiresim/a32nx/pull/5813
