### ISSUE TITLE
[BUG] PFD went completely white when taxi checklist got to FMA

### ISSUE THREAD

**Issue by maniuraPL** [flybywiresim/a32nx#594]
Version: master

As title says, Primary Flight Display went all white when checklist got to something Flight Mode Annunciator related on the taxi checklist, can't remember what exactly the name was, but ReferenceId of it is A320_TAXI_FLT_MODE_ANN. The game crashed shortly after.

To reproduce:
1. Follow standard before taxi procedures 
2. Follow the taxi checklist

Expected behavior: PFD should have a blue highlight as every instrument during checklist.

Actual behavior: PFD went all white, game crashed.

No screenshot taken, unfortunately.

**Comment by DoToAdventures** [comment]
Reproducable, fixed in newest checklist pull request by removing the highlighting for the PFD. This seems to be a limitation from Asobo and occurs whenever you wish to highlight a display.

**Comment by Coralec** [comment]
This is still occurring in the current status of the pull request.
