### ISSUE TITLE
Flight Mode Annunciator (FMA) incorrect

### ISSUE THREAD

**Issue by toffee2000** [flybywiresim/a32nx#62]
With FD and AP off, lateral and vertical modes should be blank. They currently act as though FD remains engaged. If ATHR is engaged, it should also revert to SPEED if in manual flight.

**Comment by toffee2000** [comment]
@

**Comment by Curtis-VL** [comment]
Hey @toffee2000,

I recently worked on the fix for 'THR CLB' displaying whenever the throttles were in the climb gate but the aircraft wasn't climbing, I can also look into this issue too as it'll be in the same file.

Could you contact me on Discord to discuss it whenever you're free? Curtis#1149 👍

**Comment by Curtis-VL** [comment]
I just pushed some changes that shoudl fix the issues you've mentioned. CLB, DES, and NAV will no longer appear with the FD disabled.

**Comment by toffee2000** [comment]
![FMA Issues](https://user-images.githubusercontent.com/70193215/91425563-e5b37e80-e88d-11ea-9643-cff0208f9479.png)

Still an issue. FD is off but this shows.

**Comment by toffee2000** [comment]
> 
> 
> Hey @toffee2000,
> 
> I recently worked on the fix for 'THR CLB' displaying whenever the throttles were in the climb gate but the aircraft wasn't climbing, I can also look into this issue too as it'll be in the same file. To me knowledge, the second half of this issue should have been resolved by that fix though!
> 
> Could you contact me on Discord to discuss it whenever you're free? Curtis#1149 👍

I'll do it before next week. Thanks!

**Comment by toffee2000** [comment]
![image](https://user-images.githubusercontent.com/70193215/91437295-3f22aa00-e89c-11ea-9a8a-9595b8c8c221.png)
![image](https://user-images.githubusercontent.com/70193215/91437475-8a3cbd00-e89c-11ea-9222-0602820eda7d.png)

I switched to dev branch to see if that helps. Still have the wrong FMA.

**Comment by Curtis-VL** [comment]
Hi,

Yeah, the changes are only on the dev-0.0.1 branch right now! Anything on master will be outdated. 👍 

What's incorrect about the images you just posted? So long as auto-throttle is enabled THR LVR, THR CLB, SPEED, and MACH are supposed to appear if I recall.
But I'm guessing V/S isn't supposed to be visible? Same as with CLB, DES, and NAV?

**Comment by Curtis-VL** [comment]
Right, quick update! I got in touch with a friend who's an A320 pilot and he sent me a document explaining the situation better.

I'll push an update later that when FD is disabled, the following (on top of what already doesn't appear) will no longer appear:
V/S
HDG

From this same document, it also states that auto-throttle should rever to 'SPEED' when the FD is disabled. I'll add another comment later when I have that all figured out and pushed. 👍

**Comment by toffee2000** [comment]
Thanks very much. I sent you a friend request on Discord, zachary77#3483.

**Comment by Curtis-VL** [comment]
This should be fixed as off the following pull request! #202

**Comment by Curtis-VL** [comment]
Fixed in #202 and later PRs!
