### ISSUE TITLE
Clickable spots offset from knobs and buttons

### ISSUE THREAD

**Issue by Zchulski** [flybywiresim/a32nx#7018]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-04-07T18:11:40+00:00",
  "ref": "experimental",
  "sha": "10afacbd52729f45a2be22088b677f8978d74330",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "experimental:10afacbd"
}
```

### Describe the bug

Click spots seem to be wandering.  The click spot for the altitude rotary knob on the autopilot panel seems to be just left of the actual knob.  Same thing with the toggle switch for the flight deck door.  

### Expected behavior

I would expect the click spots to be right on top of the button or rotary knobs

### Steps to reproduce

this seems to be an issue with most buttons 

### Additional info (optional)

the issue started occurring when I updated from development to experimental

**Comment by mico975** [comment]
Check that "lens correction" is off in MSFS general settings. That should solve it.

**Comment by Zchulski** [comment]
thanks, will attempt this weekend

**Comment by aguther** [comment]
Reopen the ticket when the issue persists, although there is barely anything that can be done from A32NX side. It’s with very high probability a sim issue.
